Exemple 1: Non, car le fichier parent se chargera d'attraper l'exception après que la méthode lirefichier s'est exécuté dans le main.

Exemple 2: Oui, car le fichier parent ne contient pas de try catch, donc il ne géra pas l'exception de la méthode lirefichier.